secrets:
  cloudflare-ini:
    file: cloudflared/cloudflare.ini
  origin-cert:
    file: cloudflared/cert.pem
  tunnel-config:
    file: cloudflared/config.yml
  tunnel-secret:
    file: cloudflared/60f2a096-47a8-405a-af97-f5088a41231d.json
  
services:
  nginx:
    image: nginx:mainline-alpine3.20-slim@sha256:e9293c9bedb0db866e7d2b69e58131db4c2478e6cd216cdd99b134830703983a
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    ports:
      - "8001:80"
      - "443:443"
    networks:
      - piping
      - external_app_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.5"          
          memory: 50M
        reservations:
          cpus: "0.75"
          memory: 25M

  cloudflared:
    image: williamveith/cloudflared:2024.10.0@sha256:c5551612b3678aff4dee36bb8de6c62547660e4a5507963593d9fecc089eb5fd
    container_name: cloudflared
    secrets:
      - source: origin-cert
        target: /etc/cloudflared/cert.pem
      - source: tunnel-config
        target: /etc/cloudflared/config.yml
      - source: tunnel-secret
        target: /etc/cloudflared/60f2a096-47a8-405a-af97-f5088a41231d.json
    command: tunnel --no-autoupdate run dropbox
    env_file:
      - .env
    networks:
      - piping
      - external_app_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 40M
        reservations:
          cpus: "0.75"
          memory: 20M

  certbot:
    build:
      context: .
      dockerfile: ./certbot/Dockerfile
    image: williamveith/dns-cloudflare:v2.11.0
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_lib:/var/lib/letsencrypt
    secrets:
      - source: cloudflare-ini
        target: /etc/cloudflare/cloudflare.ini
    networks:
      - piping
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 25M
        reservations:
          cpus: "0.25"
          memory: 6M

networks:
  piping:
    driver: bridge
  external_app_net:
    external: true

volumes:
  letsencrypt:
    name: "letsencrypt"
  letsencrypt_lib:
    name: "letsencrypt_lib"