secrets:
  cloudflare-ini:
    file: cloudflared/cloudflare.ini
  origin-cert:
    file: cloudflared/cert.pem
  tunnel-config:
    file: cloudflared/config.yml
  tunnel-secret:
    file: cloudflared/tunnel-credential.json
  
services:
  nginx:
    image: williamveith/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    networks:
      - piping
      - external_app_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.5"          
          memory: 50M
        reservations:
          cpus: "0.75"
          memory: 25M

  cloudflared:
    image: williamveith/cloudflared:latest
    container_name: cloudflared
    secrets:
      - source: origin-cert
        target: /etc/cloudflared/cert.pem
      - source: tunnel-config
        target: /etc/cloudflared/config.yml
      - source: tunnel-secret
        target: /etc/cloudflared/tunnel-credential.json
    command: tunnel --no-autoupdate run dropbox
    env_file:
      - .env
    networks:
      - piping
      - external_app_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 40M
        reservations:
          cpus: "0.75"
          memory: 20M

  certbot:
    image: williamveith/certbot:latest
    container_name: certbot
    env_file:
      - .env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt:/var/lib/letsencrypt
    secrets:
      - source: cloudflare-ini
        target: /etc/letsencrypt/cloudflare.ini
    networks:
      - piping
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 25M
        reservations:
          cpus: "0.25"
          memory: 6M
          
networks:
  piping:
    driver: bridge
    name: piping
  external_app_net:
    name: external_app_net
    external: true

volumes:
  letsencrypt:
    name: "letsencrypt"
  cloudflared:
    name: "cloudflared"