services:
  nginx:
    image: nginx:mainline-alpine3.20-slim@sha256:e9293c9bedb0db866e7d2b69e58131db4c2478e6cd216cdd99b134830703983a
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    ports:
      - "8001:80"
      - "443:443"
    networks:
      - piping
      - external_app_net
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "2"          
          memory: 800M
        reservations:
          cpus: "0.25"
          memory: 100M

  cloudflared:
    image: williamveith/cloudflared:2024.10.0@sha256:a6f8146d7bb9f65342856a76e32569ac518f86e321fb0ee5f94705c78be38b98
    container_name: cloudflared
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel --no-autoupdate run dropbox
    env_file:
      - .env
    networks:
      - piping
    restart: always
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          cpus: "0.25"
          memory: 15M

  certbot:
    build:
      context: .
      dockerfile: ./certbot/Dockerfile
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_lib:/var/lib/letsencrypt
      - cloudflared:/cloudflared
    networks:
      - piping
    restart: always
    deploy:
      resources:
        limits:
          memory: 20M
        reservations:
          memory: 10M

  app_server:
    image: nginxdemos/hello:0.4@sha256:a97d837baef1734cfaa19c24f333bfdf402b78de634b63b7f51c422d0270300e
    container_name: app_server
    networks:
      - piping
    expose:
      - "8000"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M

networks:
  piping:
    driver: bridge
  external_app_net:
    external: true

volumes:
  letsencrypt:
  letsencrypt_lib:
  cloudflared:
