services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - piping
      - external_app_net
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "2"          
          memory: 800M
        reservations:
          cpus: "0.25"
          memory: 100M

  cloudflared:
    image: overtime0022/cloudflared:2024.8.2
    container_name: cloudflared
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel --no-autoupdate run tiecloud
    env_file:
      - .env
    networks:
      - piping
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          cpus: "0.25"
          memory: 15M

  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_lib:/var/lib/letsencrypt
      - cloudflared:/cloudflared
    networks:
      - piping
    restart: always
    deploy:
      resources:
        limits:
          memory: 20M
        reservations:
          memory: 10M

networks:
  piping:
    driver: bridge
  external_app_net:
    external: true

volumes:
  letsencrypt:
  letsencrypt_lib:
  cloudflared:
