services:
  nginx:
    image: nginx:mainline-alpine3.20-slim
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/ssl
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - piping
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.50"          
          memory: 20M
        reservations:
          cpus: "0.25"
          memory: 10M

  cloudflared:
    image: overtime0022/cloudflared:2024.8.2
    container_name: cloudflared
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel --no-autoupdate run tiecloud
    env_file:
      - .env
    networks:
      - piping
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "5.0"          
          memory: 30M
        reservations:
          cpus: "2.50"
          memory: 15M


networks:
  piping:
    driver: bridge
