services:

  file_uploader:
    build: ./uploader  # Directory containing Dockerfile and app.py
    container_name: file_uploader
    volumes:
      - data:/data  # This mounts the /data directory for file storage
    networks:
      external_app_net:
        aliases:
          - app_server_alias
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 50M
        reservations:
          cpus: "0.5"
          memory: 25M

  rclone_uploader:
    build: ./  # Assuming the Dockerfile is in the current directory
    container_name: rclone_uploader
    volumes:
      - data:/data  # No host mount, encapsulates files in container only
      - ./rclone-config:/config/rclone
    networks:
      external_app_net:
        aliases:
          - app_server_alias
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 50M
        reservations:
          cpus: "0.5"
          memory: 25M

networks:
  external_app_net:
    name: external_app_net
    external: true

volumes:
  data:
    name: "data"
    driver_opts:
      type: "tmpfs"
      o: "size=1000m"
      device: "tmpfs"