# The alias `app_server_alias` must remain as it is used in the NGINX configuration (nginx/app.conf).
# NGINX proxies traffic to this alias, decoupling the service name from the configuration.
services:
  app_server:
    image: nginxdemos/hello:0.4@sha256:a97d837baef1734cfaa19c24f333bfdf402b78de634b63b7f51c422d0270300e
    container_name: app_server
    expose:
      - "8000"
    networks:
      external_app_net:
        aliases:
          - app_server_alias
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
        reservations:
          cpus: "0.1"
          memory: 25M

networks:
  external_app_net:
    name: external_app_net
    external: true