services:
  app_server:
    image: nginxdemos/hello:0.4@sha256:a97d837baef1734cfaa19c24f333bfdf402b78de634b63b7f51c422d0270300e
    container_name: app_server
    expose:
      - "8000"
    networks:
      - external_app_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M

networks:
  external_app_net:
    external: true